# -*- coding: utf-8 -*-
"""Heart disease detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzbeKWCVLI8dAnzUIXsiAoLsMnXz9-yt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Load the Data
# ----------------
try:
    df = pd.read_csv('heart_disease_data.csv')
    print("Data loaded successfully.")
    print(f"Dataset Shape: {df.shape}")
except FileNotFoundError:
    print("Error: The file 'heart_disease_data.csv' was not found.")
    exit()

# Display the first 5 rows
print("\n--- First 5 Rows ---")
print(df.head())

# Display basic statistical details
print("\n--- Data Description ---")
print(df.describe())

# 2. Data Visualization
# ---------------------
# Set the style for seaborn
sns.set()

# Plot the distribution of the 'target' variable
plt.figure(figsize=(6, 4))
sns.countplot(x='target', data=df)
plt.title('Distribution of Heart Disease Presence (Target)')
plt.xlabel('Target (0 = Healthy, 1 = Disease)')
plt.ylabel('Count')
plt.savefig('target_distribution.png')
plt.show()

# Plot a Correlation Heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt='.1f')
plt.title('Correlation Matrix')
plt.savefig('correlation_matrix.png')
plt.show()

# 3. Data Preprocessing & Splitting
# ---------------------------------
# Separating features (X) and target label (Y)
X = df.drop(columns='target', axis=1)
Y = df['target']

# Split data into Training and Testing sets (80% Train, 20% Test)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

print(f"\nTraining Set Size: {X_train.shape}")
print(f"Testing Set Size: {X_test.shape}")

# 4. Model Training (Logistic Regression)
# ---------------------------------------
# Logistic Regression is used for binary classification problems
model = LogisticRegression(max_iter=1000)
model.fit(X_train, Y_train)

# 5. Model Evaluation
# -------------------
# Accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

# Accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print("\n--- Model Performance ---")
print(f"Accuracy on Training data: {training_data_accuracy:.2%}")
print(f"Accuracy on Test data:     {test_data_accuracy:.2%}")

print("\n--- Classification Report ---")
print(classification_report(Y_test, X_test_prediction))

print("\n--- Confusion Matrix ---")
print(confusion_matrix(Y_test, X_test_prediction))